### ISSUE TITLE
发生了这样的报错

### ISSUE THREAD

**Issue by laowang1026** [knownsec/ksubdomain#1]
./ksubdomain_linux: error while loading shared libraries: libpcap.so.0.8: cannot open shared object file: No such file or directory

**Comment by boy-hack** [comment]
需要`libpcap.so.0.8 `，可以这样尝试
在linux下安装`libpcap-dev `后
```
locate libpcap
```
你会发现有`/usr/lib64/libpcap.so`，
```
ls -S /usr/lib64/libpcap.so /usr/lib64/libpcap.so.0.8
```

**Comment by laowang1026** [comment]
ls: 无法访问/usr/lib64/libpcap.so.0.8: 没有那个文件或目录

**Comment by laowang1026** [comment]
ok，我已经解决了，谢谢

**Comment by laowang1026** [comment]
为何格式是这种caipiao.baidu.com => CNAME lecai.jomodns.com ttl:7200 CNAME lecai.n.shifen.com ttl:1800 111.202.114.50 ttl:300

**Comment by laowang1026** [comment]
希望可以添加一个可以递归3级域名的一个功能

**Comment by HankleHigh** [comment]
老哥咋解决的能分享一下吗，centos7遇到一样的问题

**Comment by boy-hack** [comment]
> 希望可以添加一个可以递归3级域名的一个功能

加入到了todo列表 - -

**Comment by boy-hack** [comment]
> 老哥咋解决的能分享一下吗，centos7遇到一样的问题

yum如果没有libpcap可以自己编译一个0.8版本的pcap

**Comment by HankleHigh** [comment]
cd /usr/lib64/
ln libpcap.so.1 libpcap.so.0.8
好像没有找到正好0.8版本的pcap，最后是装了个其他版本的然后做了软连接，解决命令方便后来者

**Comment by laowang1026** [comment]
能加一个泛解析处理吗？

**Comment by lnm3000** [comment]
> 老哥咋解决的能分享一下吗，centos7遇到一样的问题

我是这样解决的：
先直接yum安装libpcap-devel：
# yum install libpcap-devel
然后locate一下，发现了安装的是1.5.3版本：
# locate libpcap
/usr/lib64/libpcap.so
/usr/lib64/libpcap.so.1
/usr/lib64/libpcap.so.1.5.3
然后cd到/usr/lib64目录下，ls看一下那三个文件，发现libpcap.so和libpcap.so.1都是libpcap.so.1.5.3的软链接文件。
既然这样，那就再建一个软链接文件就好了：
# ln -s libpcap.so.1.5.3 libpcap.so.0.8

**Comment by lnm3000** [comment]
> 老哥咋解决的能分享一下吗，centos7遇到一样的问题

我是这样解决的：
先直接yum安装libpcap-devel：
yum install libpcap-devel
然后locate一下，发现了安装的是1.5.3版本，定位出/usr/lib64目录下的三个文件：
locate libpcap
/usr/lib64/libpcap.so
/usr/lib64/libpcap.so.1
/usr/lib64/libpcap.so.1.5.3
然后cd到/usr/lib64目录下，ls看一下那三个文件，发现libpcap.so和libpcap.so.1都是libpcap.so.1.5.3的软链接文件。
既然这样，那就再建一个软链接文件就好了：
ln -s libpcap.so.1.5.3 libpcap.so.0.8

**Comment by h4cnull** [comment]
cp /usr/lib64/libpcap.so /usr/lib64/libpcap.so.0.8
