### ISSUE TITLE
无法使用USB有线网卡

### ISSUE THREAD

**Issue by Z-fly** [knownsec/ksubdomain#14]
![image](https://user-images.githubusercontent.com/10470892/92218078-26814800-eecb-11ea-92f7-7273d3f59713.png)

**Comment by boy-hack** [comment]
如果没有显示的话暂时可能没有办法，期待你做好后分享心得或提交代码

**Comment by Z-fly** [comment]
> 如果没有显示的话暂时可能没有办法，期待你做好后分享心得或提交代码

我也无能为力

**Comment by Z-fly** [comment]
> 如果没有显示的话暂时可能没有办法，期待你做好后分享心得或提交代码

![image](https://user-images.githubusercontent.com/10470892/92559258-cca1c900-f2a2-11ea-94df-492ec580d1dd.png)
突然就可以用了，我也不知道是什么原因。反正是WinPcap读到的

**Comment by Z-fly** [comment]
@boy-hack 建议提供命令行参数，可在多网卡时直接指定网卡ID，这样省的每次都要手动输入ID

**Comment by boy-hack** [comment]
> @boy-hack 建议提供命令行参数，可在多网卡时直接指定网卡ID，这样省的每次都要手动输入ID

有`-e`参数可以指定网卡id，v0.5版本开始会自动选择网卡
