### ISSUE TITLE
添加自动去掉泛解析记录的功能

### ISSUE THREAD

**Issue by Ares-X** [knownsec/ksubdomain#16]
rt，感觉可以使用3-5个随机域名获取泛解析记录，然后去掉结果中包含泛解析结果的子域，直接跳过存在泛解析的域名感觉有点粗暴了

**Comment by ldbfpiaoran** [comment]
不要这么改  https://github.com/knownsec/ksubdomain/issues/20 像是这个这样  泛解析都是指向一个cname  加一个cname 黑名单参数多好

**Comment by boy-hack** [comment]
新版添加了`-filter-wild`参数用于过滤泛解析
