### ISSUE TITLE
项目缺少 go.sum 文件

### ISSUE THREAD

**Issue by imlonghao** [knownsec/ksubdomain#17]
您好，

我正试图打包 ksubdomain 到 [AUR](https://aur.archlinux.org/) 方便 Archlinux 用户安装[1]，在打包的过程中发现仓库里面只有 `go.mod` 而没有 `go.sum` 文件。

在 Archlinux Wiki 的 [Go package guidelines](https://wiki.archlinux.org/index.php/Go_package_guidelines#Flag_meaning) 中推荐的打包参数中有 `-mod=readonly`，用于确保依赖的文件一致

同时，Go 官方 Wiki [Modules · golang/go Wiki](https://github.com/golang/go/wiki/Modules#should-i-commit-my-gosum-file-as-well-as-my-gomod-file) 也建议将 `go.sum` 文件一同提交到 git 仓库中。

因此，希望能一同将 `go.sum` 提交到 git 仓库中

谢谢。

---

[1] Archlinux 用户可通过 `yay -S ksubdomain` 安装

**Comment by boy-hack** [comment]
非常感谢你，已经加入了go.sum
