### ISSUE TITLE
扫描sdo.com这个域名

### ISSUE THREAD

**Issue by yckyos261** [knownsec/ksubdomain#20]
> landinfo.sdo.com => CNAME nonexist.sdo.com => 116.211.9.105
> merrick.sdo.com => CNAME nonexist.sdo.com => 116.211.9.105
> zethus.sdo.com => CNAME nonexist.sdo.com => 116.211.9.105
> jesy2474.sdo.com => CNAME nonexist.sdo.com => 116.211.9.105
> mrcoffee.sdo.com => CNAME nonexist.sdo.com => 116.211.9.105
> conversationsabouther.sdo.com => CNAME nonexist.sdo.com => 116.211.9.105
> fabi.sdo.com => CNAME nonexist.sdo.com => 116.211.9.105
> wsmith.sdo.com => CNAME nonexist.sdo.com => 116.211.9.105
> qfh.sdo.com => CNAME nonexist.sdo.com => 116.211.9.105
> newworldofnew.sdo.com => CNAME nonexist.sdo.com => 116.211.9.105
> jim-murdoch.sdo.com => CNAME nonexist.sdo.com => 116.211.9.105
> technoneedsindia.sdo.com => CNAME nonexist.sdo.com => 116.211.9.105
> sheepandchick.sdo.com => CNAME nonexist.sdo.com => 116.211.9.105
> lcm.sdo.com => CNAME nonexist.sdo.com => 116.211.9.105
> reimer.sdo.com => CNAME nonexist.sdo.com => 116.211.9.105
> zawinul.sdo.com => CNAME nonexist.sdo.com => 116.211.9.105
> gios.sdo.com => CNAME nonexist.sdo.com => 116.211.9.105
> kaufmann.sdo.com => CNAME nonexist.sdo.com => 116.211.9.105
> fortheloveofcooking-recipes.sdo.com => CNAME nonexist.sdo.com => 116.211.9.105
> resultsdon2.sdo.com => CNAME nonexist.sdo.com => 116.211.9.105
> jqe.sdo.com => CNAME nonexist.sdo.com => 116.211.9.105

全是类似这样的。。

**Comment by boy-hack** [comment]
使用`-skip-wild`跳过泛解析

**Comment by yckyos261** [comment]
[INFO] 加载内置字典
[INFO] 检测泛解析
[Warning] 域名:sdo.com 存在泛解析记录,已跳过
[INFO] 设置rate:10000pps
[INFO] DNS:[223.5.5.5 223.6.6.6 180.76.76.76 119.29.29.29 182.254.116.116 114.114.114.115]
