### ISSUE TITLE
几个小问题

### ISSUE THREAD

**Issue by puma252** [knownsec/ksubdomain#22]
1.start.go 中协程重发检测,通过遍历LocalStatus来做超时重传的校验,由于数据结构是无序的,每次都要遍历所有
的条目,是否可用队列来保存index,从队列尾部插入,从队列头部进行检查.这样只要查到某个条目没有超时,就可以停止继续遍历.
另外,这个函数中每检测一个条目就sleep 几百微秒,这导致大量的系统调用,cpu占用会比较高.

2.recv.go 中设置的bpf filter “udp and port 53” 是否改成“udp and src port 53”, 应该只关心源端口是53的dns response?

3.recv.go 中调用parser.DecodeLayers()有时会报错,打印错误信息,提示是 “no decoder for layer type ipv6”,对应代码
NewDecodingLayerParser()中只配置了layers.IPv4,是否也增加layers.IPv6的设置?

**Comment by boy-hack** [comment]
感谢你的建议～每个建议都非常实用。
1需要讨论一下，每次查询到超时的数据包，只能遍历完全部条目，还有别的方法吗，没有明白你说的队列应该怎么用，还有sleep问题应该如何优化呢

**Comment by puma252** [comment]
队列用来保存index,每次请求发送时，在插入条目到localstatus时，插入index到队列尾部，在超时逻辑中，通过从队列头部遍历队列，获取index，再通过index从localstatus中获取请求状态。由于队列是尾部插入，确保了请求按照发送的时序排列。这样，只要遍历到某个请求没有超时，就可停止遍历。当然，在判断请求发送超过25次，也需要将相关的index从队列删除。队列实现可以参考源码中的localstack简单修改下就可以。

sleep的问题，只要避免了全部遍历，应该就不需要每检查一条就sleep，可以等检查到某个条目没有超时，或者localstatus中为空，才sleep.另外，既然超时是5秒，检查超时的间隔可以改成秒级，比如1秒检查一次。这样就不会出现每秒调用几百次sleep的情况。

**Comment by boy-hack** [comment]
明白了，谢谢！

**Comment by boy-hack** [comment]
感觉建议，`v0.5.1`版本已经发布并修改了 https://github.com/knownsec/ksubdomain/releases/tag/v0.5.1
