### ISSUE TITLE
扫描bug

### ISSUE THREAD

**Issue by notwhy** [knownsec/ksubdomain#28]
例如扫描wanmei.com会出现其他的域名
zx.wanmei.com => CNAME redirect.wanmei.com => CNAME public.wanmei.gw.wscdns.com => 103.254.188.41
api.wanmei.com => CNAME shifen.wanmei.com => 221.228.210.80 => 221.228.210.81
co.wanmei.com => CNAME co.wanmei.com.wsglb0.com => 27.128.146.19 => 1.71.150.167
monitor.wanmei.com => 10.15.0.13
cps.wanmei.com => 121.9.244.130
audio.wanmei.com => CNAME audio.wanmei.ccgslb.net
kdxy.wanmei.com => CNAME redirect.wanmei.com => CNAME public.wanmei.gw.wscdns.com => 103.254.188.41
vanguard.wanmei.com => 221.228.210.19
jyh.wanmei.com => CNAME jyh.wanmei.com.wsglb0.com => 1.71.150.167 => 27.128.146.19
hooks.pot.tencent.com => 115.159.130.208
lyncdiscover.lenovo.com => CNAME join.gtm.lenovo.com
webresource.eastmoney.com => 180.163.69.224
会不会被其他数据包干扰？

**Comment by notwhy** [comment]
![image](https://user-images.githubusercontent.com/11815957/96398581-ccc8a900-11fe-11eb-9c65-8b5ec196a9c6.png)
一直存在，可复现

**Comment by boy-hack** [comment]
ksubdomain在运行时可能会被其他的数据包干扰。
在 https://github.com/knownsec/ksubdomain/blob/master/core/start.go
31行 `flagID := uint16(RandInt64(400, 654))` 
其他dns数据包返回的dnsid前三位是flagID的时候就会被抓取，可以修改flagID为一个比较偏僻的数字，取值是(100,654)

**Comment by boy-hack** [comment]
> recv里面可以验证一下来源ip是不是来自指定的dns服务器，避免数据包干扰

是一个好方法

**Comment by boy-hack** [comment]
新版添加了`-check-origin`参数，用于解决此问题

**Comment by notwhy** [comment]
爆粗了
echo "hongen.com" | ./ksubdomain -check-origin -filter-wild -o 1.txt

panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
ksubdomain/core.FilterWildCard(0x7ffc4116cdc7, 0x5, 0x0, 0x68ef3c, 0x1)
	/media/psf/AllFiles/Users/boyhack/GolandProjects/ksubdomain/core/filterwild.go:48 +0xc39
ksubdomain/core.Start(0xc000139cc0)
	/media/psf/AllFiles/Users/boyhack/GolandProjects/ksubdomain/core/start.go:180 +0xc66
main.main()
	/media/psf/AllFiles/Users/boyhack/GolandProjects/ksubdomain/cmd/ksubdomain.go:45 +0x38

**Comment by notwhy** [comment]
@boy-hack

**Comment by boy-hack** [comment]
我本地测试没有发生报错，不过还是修复了一下，需要编译

**Comment by notwhy** [comment]
@boy-hack 本地编译没问题了，建议发个稳定版本
