### ISSUE TITLE
False alarm rate is too high

### ISSUE THREAD

**Issue by rgzn-aiyun** [knownsec/ksubdomain#36]
Hi, the scanning speed of this tool is very fast, but the false positive rate is too high. Only half of the more than 1,000 domain names detected by httpx are normal domain names.

**Comment by rgzn-aiyun** [comment]
@boy-hack

**Comment by boy-hack** [comment]
Ksubdomain gets is the result in dns and you can specify some trusted dns, use the `-s` parameter

**Comment by rgzn-aiyun** [comment]
Use the -s parameter to scan for half an hour?

**Comment by rgzn-aiyun** [comment]
Success:0 Sent:2854 Recved:0 Faild:0[Warning] SerializeLayers faild:Invalid destination IPv4 address (wrong length of 0 bytes instead of 4)
Failed to send?
