### ISSUE TITLE
俩个爆破场景

### ISSUE THREAD

**Issue by notwhy** [knownsec/ksubdomain#39]
1.
aaa-bbb-ccc.domain.com
我想只爆破aaa参数 输入-bbb-ccc.domain.com提供字典爆破
2.
aaa-bbb-ccc.domain.com
把aaa替换为{alphabet}{alphabet}{alphabet} 三位字母进行爆破
100-bbb-ccc.domain.com
把100替换为{num}{num}{num} 三位字母进行爆破

**Comment by boy-hack** [comment]
可以自行生成字典然后使用`-verify`进行验证
