### ISSUE TITLE
mac 无法运行

### ISSUE THREAD

**Issue by Junm0** [knownsec/ksubdomain#6]
mac 10.15.6 提示command not found
<img width="418" alt="截屏2020-09-02 18 11 18" src="https://user-images.githubusercontent.com/57264045/91968763-b4ccc100-ed47-11ea-84dd-ee8b26f5bf0b.png">

**Comment by Mr-xn** [comment]
> mac 10.15.6 提示command not found
> <img alt="截屏2020-09-02 18 11 18" width="418" src="https://user-images.githubusercontent.com/57264045/91968763-b4ccc100-ed47-11ea-84dd-ee8b26f5bf0b.png">

老弟 你注意下权限 OK？`chmod +x ksubdomain_mac` 
![Snipaste_2020-09-02_18-51-46.png](https://i.loli.net/2020/09/02/p8dQMXYFk4LjVS3.png)
