### ISSUE TITLE
请问怎么选择网卡？

### ISSUE THREAD

**Issue by zglaozhu** [knownsec/ksubdomain#7]
![image](https://user-images.githubusercontent.com/31888299/91970137-cadb8100-ed49-11ea-84c2-43fbe6de334d.png)
输入网卡哪一个  IP address？ Description?
试了都出错

**Comment by Mr-xn** [comment]
> ![image](https://user-images.githubusercontent.com/31888299/91970137-cadb8100-ed49-11ea-84c2-43fbe6de334d.png)
> 输入网卡哪一个 IP address？ Description?
> 试了都出错

选择你能够上网的那种网卡试试啊 还有权限 用管理员权限窗口 试试

**Comment by zglaozhu** [comment]
> > ![image](https://user-images.githubusercontent.com/31888299/91970137-cadb8100-ed49-11ea-84c2-43fbe6de334d.png)
> > 输入网卡哪一个 IP address？ Description?
> > 试了都出错
> 
> 选择你能够上网的那种网卡试试啊 还有权限 用管理员权限窗口 试试

不是权限，我输入192.168这种，提示要输入数字

**Comment by Mr-xn** [comment]
> > > ![image](https://user-images.githubusercontent.com/31888299/91970137-cadb8100-ed49-11ea-84c2-43fbe6de334d.png)
> > > 输入网卡哪一个 IP address？ Description?
> > > 试了都出错
> > 
> > 
> > 选择你能够上网的那种网卡试试啊 还有权限 用管理员权限窗口 试试
> 
> 不是权限，我输入192.168这种，提示要输入数字

醉了 你没看前面有么。。。[0] [1] [2] [3] [4]...这种啊 前面标识的有 你看下你的上网的IP 在输入对应的数字就行了

**Comment by zglaozhu** [comment]
> > > > ![image](https://user-images.githubusercontent.com/31888299/91970137-cadb8100-ed49-11ea-84c2-43fbe6de334d.png)
> > > > 输入网卡哪一个 IP address？ Description?
> > > > 试了都出错
> > > 
> > > 
> > > 选择你能够上网的那种网卡试试啊 还有权限 用管理员权限窗口 试试
> > 
> > 
> > 不是权限，我输入192.168这种，提示要输入数字
> 
> 醉了 你没看前面有么。。。[0] [1] [2] [3] [4]...这种啊 前面标识的有 你看下你的上网的IP 在输入对应的数字就行了

ok了 谢谢啊

**Comment by Mr-xn** [comment]
@zglaozhu 关了这个 issue 吧
