### ISSUE TITLE
随机选择DNS的问题

### ISSUE THREAD

**Issue by CoolSpring8** [knownsec/ksubdomain#8]
在 SendDog 的 ChoseDns 方法中，手动指定的 resolvers 列表中的最后一个 DNS 总是不会被选取（如果列表中仅包含一个 DNS，则会发生 panic: invalid argument to Intn）

https://github.com/knownsec/ksubdomain/blob/c96db177c3cfaf0fe5622e5753a6f78de700d366/core/send.go#L54-L55

> Intn returns, as an int, a non-negative pseudo-random number in [0,n) from the default Source. It panics if n <= 0. ([doc](https://golang.org/pkg/math/rand/#Intn))

解决方案：

```go
return d.dns[rand.Intn(len(d.dns))] 
```

**Comment by boy-hack** [comment]
你说的问题确实存在，不过你的解决方法可能会造成数组索引溢出.

**Comment by CoolSpring8** [comment]
> 你说的问题确实存在，不过你的解决方法可能会造成数组索引溢出.

啊，我觉得不会溢出吧……

rand.Intn(length) 返回的是 [0,length) 前闭后开区间内的整数，也就是 [0, 1, 2, 3, ..., length-1]，最小是 d.dns[0]，最多能取到 d.dns[length-1]，似乎并没有问题啊

由于给长度减了1，现在“最后一个 DNS 总是不会被选取”的情况还是没有解决

**Comment by boy-hack** [comment]
哦哦，我以为两个都是闭区间呢。。
