### ISSUE TITLE
反馈个问题

### ISSUE THREAD

**Issue by lnm3000** [knownsec/ksubdomain#9]
复现了两次，当success大概1037左右个域名的时候，程序就会卡住不动：
![image](https://user-images.githubusercontent.com/22117516/92018989-7efbfc80-ed88-11ea-8839-b91e200767de.png)
环境：阿里云VPS、CentOS 7

**Comment by boy-hack** [comment]
发了500w包只收到了1000多个，可能是和网速有关吧？

**Comment by BeingEasy** [comment]
貌似mac使用 -b 1m 会导致微信消息 难以发送

**Comment by lnm3000** [comment]
> 发了500w包只收到了1000多个，可能是和网速有关吧？调整下速度或换个目标试试，如果还存在，请把执行的指令和机器配置也贴一下

感谢感谢，确实是网络的问题，可能是被ban了VPS的IP之类的，换了个目标就没有这个问题了。
